export { createLinear, interpolateNumber, interpolateColor } from './linear'
export { createTime } from './time'
export { createOrdinal } from './ordinal'
export { createBand } from './band'
export { createPoint } from './point'
export { createThreshold } from './threshold'
export { createQuantize } from './quantize'
